import openai
import os
from typing import Any, Dict


class GeneralAgent(object):
    """A general agent that interacts with OpenAI's models."""

    role_: str = ""

    def __init__(self, model: str = 'gpt-3.5-turbo'):
        """
        Initializes a GeneralAgent.

        Args:
            model (str, optional): The name of the model to use (default is 'gpt-3.5-turbo').
        """
        self.system_message_: Dict[str, Any] = {"role": "system", "content": self.role_}
        self.model_: str = model

    def query(self, user_query: str, temperature: int = 0) -> str:
        """
        Sends a user query to OpenAI and returns the response.

        Args:
            user_query (str): The user's query.

        Returns:
            str: The response generated by OpenAI.
        """
        print("####################### Sending request to OpenAI:  #########################")  # With automatic line wrapping
        print(user_query)
        print("####################### Response from OpenAI: #########################")
        messages = [self.system_message_,
                    {"role": "user", "content": user_query}]
        response = openai.ChatCompletion.create(
            model=self.model_, 
            messages=messages,
            temperature=temperature,
        )
        answer = response.choices[0]["message"]["content"]
        print(answer)
        print("####################### Ended & Returned the response. #########################")
        return answer


class Researcher(GeneralAgent):
    """A specialized agent act as professional researcher."""

    role_: str = "You are a professional researcher, you have a PhD, and you are a professor at Stanford University. \
        Your expertise is in reading and summarizing scientific papers. When given a query, a series of paper content as context, \
        and the title of the paper, you always return a very detailed answer to the query."
